version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  # rtsptoweb:
  roverr_rtsp_stream:
    restart: always
    image: ghcr.io/deepch/rtsptoweb:latest
    volumes:
      - ./RtspConfig.json:/config/config.json
    ports:
      - "8080:8080"


  # teleicu_middleware
  teleicu_middleware:
    restart: always
    build: 
      dockerfile: dev.Dockerfile
    command: ["python", "manage.py" , "runserver" , "0.0.0.0:8090"]
    volumes:
      - .:/app
    depends_on:
      - redis
      - roverr_rtsp_stream
      - db
    env_file:
      - ./.env
    ports:
      - "8090:8090"

  celery:
    build: 
      dockerfile: dev.Dockerfile
    command: ["sh", "-c", "/app/start-celery.sh"]
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - teleicu_middleware

  # proxies requests to internal services
  reverse-proxy:
    restart: always
    image: ghcr.io/coronasafe/teleicu_nginx/teleicu_nginx:latest
    depends_on:
      - teleicu_middleware
    ports:
      - "8001:8001"

volumes:
  postgres-data:
